server:
  port: 8089

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/restaurants/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/delivery/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**
        - id: loyalty-service
          uri: lb://loyalty-service
          predicates:
            - Path=/loyalty/**
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/search/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
